channels:
  - https://repo.anaconda.com/pkgs/snowflake
  - defaults
dependencies:
  - snowflake-snowpark-python[pandas]
  - snowflake-ml-python
  - cryptography
  - pandas
  - streamlit
  - scikit-learn
  - ipykernel
  - pip:
    - snowflake-ingest
